# permissions for end users to view bhagyatests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bhagyatest-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - bhagyatests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - bhagyatests/status
  verbs:
  - get
