# permissions for end users to edit bhagyatests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bhagyatest-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - bhagyatests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - bhagyatests/status
  verbs:
  - get
