# permissions for end users to edit localoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localoperator-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - localoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - localoperators/status
  verbs:
  - get
