
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - bhagyas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - bhagyas/finalizers
  verbs:
  - update
- apiGroups:
  - cache.example.com
  resources:
  - bhagyas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.example.com
  resources:
  - helmcharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - helmcharts/finalizers
  verbs:
  - update
- apiGroups:
  - cache.example.com
  resources:
  - helmcharts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.example.com
  resources:
  - localoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - localoperators/finalizers
  verbs:
  - update
- apiGroups:
  - cache.example.com
  resources:
  - localoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
