apiVersion: cache.example.com/v1
kind: LocalOperator
metadata:
  name: local-volume
spec:
  # Add fields here
  namespace: "local-storage"
  volumeMode: "Block"
  # volumeMode: "Filesystem"
  devicePath: "/dev/xvdc"
  label:
    key: "storage"
    value: "localblock"
    # value: "lfile"
  fstype: ""