apiVersion: cache.example.com/v1
kind: HelmChart
metadata:
  name: aws-ebs-csi-driver
spec:
  helm-repo-name: aws-ebs-csi-driver
  helm-repo-url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  helm-chart-name: aws-ebs-csi-driver
  helm-chart-version: "0.10.0"
  namespace: kube-system
  params:
#    - name: "enableVolumeScheduling"
#     value: "false"
    - name: "enableVolumeResizing"
      value: "false"
#    - name: "enableVolumeSnapshot"
#      value: "false"

