kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devtest-file-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: sat-local-file-gold